[package]
name = "zshleyp/remote"
description = "Remote event wrapper with automatic buffering"
license = "MIT"
authors = ["Flipitagainpls, zshleyp"]
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
Signal = "sleitnick/signal@2.0.3"
BufferEncoder = "anexpia/bufferencoder@1.4.0"
